import './globals.css'
import { Analytics } from '@vercel/analytics/react';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta name="google-site-verification" content="qDq4mJkHEXvHWPMjoOOHfQlaj50tTqhjRTILDY6pkGc" />
      <body className={inter.className}>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
